### ISSUE TITLE
bullet pkgconfig file is broken

### ISSUE THREAD

**Issue by zmike** [vtorri/ewpi#13]
The `Libs` and `Cflags` variables exported by bullet.pc are busted: they use the mingw path `/opt/ewpi_64/xyz` but they need to use the Windows style `C:/msys64/opt/ewpi_64/xyz` in order to work correctly.

**Comment by vtorri** [comment]
actually, all the pc files of packages built with cmake have the same problem

**Comment by vtorri** [comment]
fixed with 00d7273adab87dfebf1c3f16c414598cde0003c5
