### ISSUE TITLE
Fails to install lz4 binaries

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#14]
I see the following issue when trying to build lz4 on Fedora (make.log):

 1 make[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
  2 compiling dynamic library 1.9.1
  3 x86_64-w64-mingw32-gcc -I/ewpi-64-install//include -DXXH_NAMESPACE=LZ4_ -O2 -pipe -march=x86-64 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wstrict-aliasing=1  -L/ewpi-64-install//lib -s -s    hared lz4.c lz4frame.c lz4hc.c xxhash.c -fPIC -fvisibility=hidden -Wl,-soname=liblz4.so.1 -o liblz4.1
  4 creating versioned links
  5 cp -p liblz4.1 liblz4.so.1
  6 cp -p liblz4.1 liblz4.so
  7 creating pkgconfig
  8 sed -e 's|@PREFIX@|/ewpi-64-install/|' \
  9          -e 's|@LIBDIR@|/ewpi-64-install//lib|' \
 10          -e 's|@INCLUDEDIR@|/ewpi-64-install//include|' \
 11          -e 's|@VERSION@|1.9.1|' \
 12           liblz4.pc.in >liblz4.pc
 13 install -d -m 755 /ewpi-64-install//lib/pkgconfig/ /ewpi-64-install//include/ /ewpi-64-install//lib/ /ewpi-64-install//bin/
 14 install -m 644 liblz4.pc /ewpi-64-install//lib/pkgconfig/
 15 Installing libraries
 16 install -m 755 liblz4.1 /ewpi-64-install//lib
 17 cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so.1
 18 cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so
 19 Installing headers in /ewpi-64-install//include
 20 install -m 644 lz4.h /ewpi-64-install//include/lz4.h
 21 install -m 644 lz4hc.h /ewpi-64-install//include/lz4hc.h
 22 install -m 644 lz4frame.h /ewpi-64-install//include/lz4frame.h
 23 lz4 libraries installed
 24 make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
 25 make[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
 26 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4.o     ../lib/lz4.c
 27 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4fra    me.o ../lib/lz4frame.c
 28 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4hc.    o ../lib/lz4hc.c
 29 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/xxhash    .o ../lib/xxhash.c
 30 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o bench.o bench    .c
 31 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o dat    agen.c
 32 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4cli.o lz4c    li.c
 33 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4io.o lz4io    .c
 34 x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_ -L/ewpi-64-install//    lib -s ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
 35 Installing binaries
 36 install: cannot stat 'lz4': No such file or directory
 37 make[1]: *** [Makefile:151: install] Error 1
 38 make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
 39 make: *** [Makefile:93: install] Error 2

**Comment by vtorri** [comment]
in lz4-1.9.1/programs/Makefile can you remove the @ in the install rule (lines 150 to 159) to see the commands ?

**Comment by Stefan-Schmidt** [comment]
ake[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
install -d -m 755 /ewpi-64-install//lib/pkgconfig/ /ewpi-64-install//include/ /ewpi-64-install//lib/ /ewpi-64-install//bin/
install -m 644 liblz4.pc /ewpi-64-install//lib/pkgconfig/
Installing libraries
install -m 755 liblz4.1 /ewpi-64-install//lib
cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so.1
cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so
Installing headers in /ewpi-64-install//include
install -m 644 lz4.h /ewpi-64-install//include/lz4.h
install -m 644 lz4hc.h /ewpi-64-install//include/lz4hc.h
install -m 644 lz4frame.h /ewpi-64-install//include/lz4frame.h
lz4 libraries installed
make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
make[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_ -L/ewpi-64-install//lib -s ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
echo Installing binaries
Installing binaries
install -d -m 755 /ewpi-64-install//bin/ /ewpi-64-install//share/man/man1/
install -m 755 lz4 /ewpi-64-install//bin/lz4
install: cannot stat 'lz4': No such file or directory
make[1]: *** [Makefile:151: install] Error 1
make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
make: *** [Makefile:93: install] Error 2

There is a lz4.exe binary build inside the programs subdir. No idea why it fails to install it.

**Comment by vtorri** [comment]
it's not normal. What you have here is a compilation for linux, not Windows. Here is my make.log : 

http://codepad.org/YVze8A5B

try to extract and compile lz4 again : 

rm -rf /ewpi-64-install/share/ewpi/packages/lz4/extracted /ewpi-64-install/share/ewpi/packages/lz4/installed /ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1

and launch ewpi again

**Comment by Stefan-Schmidt** [comment]
Done, did not change anything. I had been doing clean builds a few times before, always with the same result. Here is the full log again after the cleaned build:

make[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
compiling dynamic library 1.9.1
x86_64-w64-mingw32-gcc -I/ewpi-64-install//include -DXXH_NAMESPACE=LZ4_ -O2 -pipe -march=x86-64 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wstrict-aliasing=1  -L/ewpi-64-install//lib -s -shared lz4.c lz4frame.c lz4hc.c xxhash.c -fPIC -fvisibility=hidden -Wl,-soname=liblz4.so.1 -o liblz4.1
creating versioned links
cp -p liblz4.1 liblz4.so.1
cp -p liblz4.1 liblz4.so
creating pkgconfig
sed -e 's|@PREFIX@|/ewpi-64-install/|' \
         -e 's|@LIBDIR@|/ewpi-64-install//lib|' \
         -e 's|@INCLUDEDIR@|/ewpi-64-install//include|' \
         -e 's|@VERSION@|1.9.1|' \
          liblz4.pc.in >liblz4.pc
install -d -m 755 /ewpi-64-install//lib/pkgconfig/ /ewpi-64-install//include/ /ewpi-64-install//lib/ /ewpi-64-install//bin/
install -m 644 liblz4.pc /ewpi-64-install//lib/pkgconfig/
Installing libraries
install -m 755 liblz4.1 /ewpi-64-install//lib
cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so.1
cp -p liblz4.1 /ewpi-64-install//lib/liblz4.so
Installing headers in /ewpi-64-install//include
install -m 644 lz4.h /ewpi-64-install//include/lz4.h
install -m 644 lz4hc.h /ewpi-64-install//include/lz4hc.h
install -m 644 lz4frame.h /ewpi-64-install//include/lz4frame.h
lz4 libraries installed
make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/lib'
make[1]: Entering directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4.o ../lib/lz4.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4frame.o ../lib/lz4frame.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/lz4hc.o ../lib/lz4hc.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o ../lib/xxhash.o ../lib/xxhash.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o bench.o bench.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o datagen.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4cli.o lz4cli.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4io.o lz4io.c
x86_64-w64-mingw32-gcc -O2 -pipe -march=x86-64 -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1  -I/ewpi-64-install//include -I../lib -DXXH_NAMESPACE=LZ4_ -L/ewpi-64-install//lib -s ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
Installing binaries
install: cannot stat 'lz4': No such file or directory
make[1]: *** [Makefile:151: install] Error 1
make[1]: Leaving directory '/ewpi-64-install/share/ewpi/packages/lz4/lz4-1.9.1/programs'
make: *** [Makefile:93: install] Error 2

**Comment by vtorri** [comment]
should be fixed in git, please test

**Comment by Stefan-Schmidt** [comment]
The commit setting TARGET_OS for the lz4 make command did the trick. The binaries are now successfully installed.
