### ISSUE TITLE
Packages no longer build on Linux after verbose option commit

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#15]
Since the verbose option was added already the first package (pkg-config) fails to build with this in make.log:

make: *** No rule to make target 'no'.  Stop.

Somehow the "no" option was put in as a make target. I do not have --verbose defined on my commandline.

Reverting the verbose option commit (237283e679e0eb7cf41f045710f9a5b3f36fea6b) brings ewpi back to a working state for me.

**Comment by vtorri** [comment]
i've commit a fix which works for Ubuntu 18.04 LTS

**Comment by Stefan-Schmidt** [comment]
The problem is still there. I just found out it only shows when no --jobs argument is set. If you give the jobs number to ewpi it will happily work.

Seems like something got wrong with passing the args from ewpi to the instal.sh scripts when you added the verbose option.

**Comment by vtorri** [comment]
ha. I don't have this problem, but ok, it's the beginning of something i can investigate. thank you

**Comment by vtorri** [comment]
so config.log is correctly filled, right ?

**Comment by vtorri** [comment]
can you try this (all in git repo)  : 
in ewpi/common.sh  : replace verbmake="V=1" and verbmake="V=0" with respectively : 
verbmake="1" and verbmake="0"

and in pkgconfig/install.sh, replace $verbmake with V=$verbmake

**Comment by vtorri** [comment]
or : 

make -j $5 $verbmake
with
make -j$5 $verbmake

or  with : make $verbmake -j $5

**Comment by Stefan-Schmidt** [comment]
The problem really is here that $5 is "no" when no --jobs option is given. (I echoed it from the install.sh script)

Make will interpret this as -j (valid as option without argument) and then the target "no".

Which means the handling of the -j option is wrong in ewpi. If none is given it should pass an empty string and if a number is given it should pass the job number as integer.

**Comment by vtorri** [comment]
is it fixed now ?

**Comment by Stefan-Schmidt** [comment]
I just run another fresh build from HEAD (f887af697de0d77df7806ea01bc3011cfe0bb929) and I see the make: *** No rule to make target 'no'.  Stop. problem in the libsnappy package.

The rest seems to work now

**Comment by Stefan-Schmidt** [comment]
And just to be clear. If I run this with --jobs=2 for example it works fine

**Comment by vtorri** [comment]
and now ?

**Comment by Stefan-Schmidt** [comment]
With todays HEAD I am not seeing this issue anymore
