### ISSUE TITLE
conflicting type compile error in libmysofa

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#16]
During the compile of libmysofa I get many conflicting type errors and the builds errors out.

  1 [  9%] Building C object src/CMakeFiles/mysofa-shared.dir/hrtf/reader.c.obj
  2 [  9%] Building C object src/CMakeFiles/mysofa-shared.dir/hdf/superblock.c.obj
  3 In file included from /usr/include/stdlib.h:394,
  4                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:8:
  5 /usr/include/sys/types.h:108:19: error: conflicting types for 'ssize_t'
  6  typedef __ssize_t ssize_t;
  7                    ^~~~~~~
  8 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
  9                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 10                  from /usr/include/string.h:33,
 11                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:7:
 12 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:45:35: note: previous declaration of 'ssize_t' was here
 13  __MINGW_EXTENSION typedef __int64 ssize_t;
 14                                    ^~~~~~~
 15 In file included from /usr/include/sys/types.h:129,
 16                  from /usr/include/stdlib.h:394,
 17                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:8:
 18 /usr/include/bits/types/time_t.h:7:18: error: conflicting types for 'time_t'
 19  typedef __time_t time_t;
 20                   ^~~~~~
 21 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
 22                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 23                  from /usr/include/string.h:33,
 24                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:7:
 25 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:138:20: note: previous declaration of 'time_t' was here
 26  typedef __time64_t time_t;
 27                     ^~~~~~
 28 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:9:
 29 /usr/include/errno.h:38: warning: "errno" redefined
 30  # define errno (*__errno_location ())
 31
 32 In file included from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 33                  from /usr/include/string.h:33,
 34                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:7:
 35 /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:19: note: this is the location of the previous definition
 36  #define errno (*_errno())
 37
 38 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/reader.h:11,
 39                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:11:
 40 /usr/include/stdint.h:90:27: error: conflicting types for 'uintptr_t'
 41  typedef unsigned long int uintptr_t;
 42                            ^~~~~~~~~
 43 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
 44                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 45                  from /usr/include/string.h:33,
 46                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:7:
 47 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:75:44: note: previous declaration of 'uintptr_t' was here
 48  __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
 49                                             ^~~~~~~~~
 50 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/reader.h:11,
 51                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:11:
 52 /usr/include/stdint.h:106: warning: "__INT64_C" redefined
 53  #  define __INT64_C(c) c ## L
 54
 55 <built-in>: note: this is the location of the previous definition
 56 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/reader.h:11,
 57                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hdf/superblock.c:11:
 58 /usr/include/stdint.h:107: warning: "__UINT64_C" redefined
 59  #  define __UINT64_C(c) c ## UL
 60
 61 <built-in>: note: this is the location of the previous definition
 62 make[2]: *** [src/CMakeFiles/mysofa-shared.dir/build.make:78: src/CMakeFiles/mysofa-shared.dir/hdf/superblock.c.obj] Error 1
 63 make[2]: *** Waiting for unfinished jobs....
 64 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:9:
 65 /usr/include/stdio.h:77:19: error: conflicting types for 'ssize_t'
 66  typedef __ssize_t ssize_t;
 67                    ^~~~~~~
 68 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
 69                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 70                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:8:
 71 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:45:35: note: previous declaration of 'ssize_t' was here
 72  __MINGW_EXTENSION typedef __int64 ssize_t;
 73                                    ^~~~~~~
 74 In file included from /usr/include/sys/types.h:129,
 75                  from /usr/include/stdlib.h:394,
 76                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:10:
 77 /usr/include/bits/types/time_t.h:7:18: error: conflicting types for 'time_t'
 78  typedef __time_t time_t;
 79                   ^~~~~~
 80 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
 81                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 82                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:8:
 83 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:138:20: note: previous declaration of 'time_t' was here
 84  typedef __time64_t time_t;
 85                     ^~~~~~
 86 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/mysofa.h:13,
 87                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:15:
 88 /usr/include/stdint.h:90:27: error: conflicting types for 'uintptr_t'
 89  typedef unsigned long int uintptr_t;
 90                            ^~~~~~~~~
 91 In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7,
 92                  from /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/include/stddef.h:1,
 93                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:8:
 94 /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:75:44: note: previous declaration of 'uintptr_t' was here
 95  __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
 96                                             ^~~~~~~~~
 97 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/mysofa.h:13,
 98                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:15:
 99 /usr/include/stdint.h:106: warning: "__INT64_C" redefined
100  #  define __INT64_C(c) c ## L
101
102 <built-in>: note: this is the location of the previous definition
103 In file included from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/mysofa.h:13,
104                  from /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:15:
105 /usr/include/stdint.h:107: warning: "__UINT64_C" redefined
106  #  define __UINT64_C(c) c ## UL
107
108 <built-in>: note: this is the location of the previous definition
109 /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c: In function 'readValue':
110 /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:32:10: warning: conversion from 'long long unsigned int' to 'uint64_t' {aka 'long unsigned int'} changes value from '18446744073709551615' to '4294967295' [-Woverflow]
111    return 0xffffffffffffffffLL;
112           ^~~~~~~~~~~~~~~~~~~~
113 /home/stefan/EFL/ewpi/install-dir/share/ewpi/packages/libmysofa/libmysofa-0.7/src/hrtf/reader.c:37:11: warning: conversion from 'long long unsigned int' to 'uint64_t' {aka 'long unsigned int'} changes value from '18446744073709551615' to '4294967295' [-Woverflow]
114     return 0xffffffffffffffffLL;
115            ^~~~~~~~~~~~~~~~~~~~
116 make[2]: *** [src/CMakeFiles/mysofa-shared.dir/build.make:64: src/CMakeFiles/mysofa-shared.dir/hrtf/reader.c.obj] Error 1
117 make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/mysofa-shared.dir/all] Error 2
118 make: *** [Makefile:152: all] Error 2

**Comment by Stefan-Schmidt** [comment]
[config.log](https://github.com/vtorri/ewpi/files/3310327/config.log)
[make.log](https://github.com/vtorri/ewpi/files/3310328/make.log)

Newest config and make logs

**Comment by vtorri** [comment]
can you also give src/Makefile please ?

**Comment by Stefan-Schmidt** [comment]
[Makefile.txt](https://github.com/vtorri/ewpi/files/3311133/Makefile.txt)

Rename to .txt as Github forces me to have a file suffix...

**Comment by vtorri** [comment]
have you tried without ccache ?

**Comment by vtorri** [comment]
can you compress the libmysofa directory (the one with sources) and send it by  mail please ?

**Comment by Stefan-Schmidt** [comment]
I have not forgotten about this, just to many other things to to care of.

The whole dir is 155MB, even compressed that would not work via mail. Let me find a way to upload and give you access

**Comment by Stefan-Schmidt** [comment]
Just a quick update (sorry for the delay). I am still seeing this with latest HEAD (f887af697de0d77df7806ea01bc3011cfe0bb929).

Will try to make sure it runs without ccache and if that does not help prepare a dump of the libmysofa dir

**Comment by Stefan-Schmidt** [comment]
This is what I found in the config log as a warning:

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE

**Comment by Stefan-Schmidt** [comment]
I guess we can ignore the last comment. This only shows when running the build a second time. On the first build I am not seeing the warning. Apparently you can not change the toolchain on the second run thus the warning is issued.

**Comment by Stefan-Schmidt** [comment]
Full libmysof dir uploaded here: https://file.io/ICjNqD

**Comment by Stefan-Schmidt** [comment]
With todays HEAD I am not seeing this issue anymore
