### ISSUE TITLE
Ewpi fails to install package libavif-0.9.2

### ISSUE THREAD

**Issue by TripleSM** [vtorri/ewpi#24]
:: Installation of packages...
( 1/90) pkf-config-1.7.3          [                                        ]   1%xz: (stdout): Write error: Invalid argument
( 6/90) libpng-1.6.37             [##                                      ]   6%xz: (stdout): Write error: Invalid argument
( 8/90) gettext-0.21.0            [###                                     ]   8%xz: (stdout): Write error: Invalid argument
( 9/90) xz-5.2.5                  [####                                    ]  10%xz: (stdout): Write error: Invalid argument
(17/90) nasm-2.14.2               [#######                                 ]  18%xz: (stdout): Write error: Invalid argument
(18/90) libdav1d-0.9.2            [########                                ]  20%xz: (stdout): Write error: Invalid argument
(20/90) libaom-3.1.2              [########                                ]  22%Note: switching to '8f85bb1d686647d0f7dc1e7220f94f55193d2c89'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at ae2be8030 Update AUTHORS,CHANGELOG,CMakeLists.txt for v3.1.2
(21/90) libavif-0.9.2             [#########                               ]  23% Can not install libavif

**Comment by vtorri** [comment]
please paste $prefix/share/ewpi/packages/libavif/config.log and (if it exists) $prefix/share/ewpi/packages/libavif/make.log

thank you

**Comment by TripleSM** [comment]
I found the below info in the make.log file.
--------------------------------------------------

ninja: fatal: invalid -j parameter

--------------------------------------------------

**Comment by vtorri** [comment]
ok, something to fix

relaunch ewpi with --jobs=8 (or whatever number of jobs you want)

thank you for the report

**Comment by TripleSM** [comment]
Thank you very much for you workaround.
It has solve the issue.

**Comment by vtorri** [comment]
it should be fixed in git, now. If not, re-open the issue. Thank you
