### ISSUE TITLE
Ewpi fails to install package gettext-0.21.0

### ISSUE THREAD

**Issue by TripleSM** [vtorri/ewpi#25]
:: Installation of packages...
( 1/83) gettext-0.21.0            [                                        ]   1%xz: (stdout): Write error: Invalid argument
 Can not install gettext
 
make.log
```
Making install in doc
make[1]: Entering directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/doc'
make[2]: Entering directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/doc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/doc'
make[1]: Leaving directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/doc'
Making install in intl
make[1]: Entering directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/intl'
make  install-am
make[2]: Entering directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/intl'
  CCLD     libintl.la
libtool:   error: 'dcgettext.lo' is not a valid libtool object
make[2]: *** [Makefile:1643: libintl.la] Error 1
make[2]: Leaving directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/intl'
make[1]: *** [Makefile:1789: install] Error 2
make[1]: Leaving directory '/opt/ewpi_64/share/ewpi/packages/gettext/gettext-0.21/gettext-runtime/intl'
ake: *** [Makefile:1467: install-recursive] Error 1
```

**Comment by vtorri** [comment]
is gettext-devel package installed with MSYS2 ?

**Comment by vtorri** [comment]
to recompile a package completely : remove $prefix/share/ewpi/packages/the_package (in case it would help)

**Comment by TripleSM** [comment]
> 
> 
> is gettext-devel package installed with MSYS2 ?

Yes I found it.
$ pacman -Qi gettext-devel
Name            : gettext-devel
Version         : 0.19.8.1-1
Description     : GNU Internationalization development utilities
Architecture    : x86_64
URL             : https://www.gnu.org/software/gettext/
Licenses        : GPL
Groups          : development  base-devel
Provides        : None
Depends On      : gettext=0.19.8.1  libiconv-devel
Optional Deps   : cvs: for autopoint tool
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.74 MiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Wed, May 31, 2017 4:25:53 PM
Install Date    : Mon, Oct 4, 2021 2:58:49 AM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by TripleSM** [comment]
> 
> 
> to recompile a package completely : remove $prefix/share/ewpi/packages/the_package (in case it would help)

Remove package gettext from /opt/ewpi_64/share/ewpi/packages/ , and re-run ewpi again fix the error.
Thank you very much.

**Comment by vtorri** [comment]
ok, closing then. Thank you for testing ewpi :)
