### ISSUE TITLE
Compilation error in gst-plugins-base-1.22.1 (ewpi-1.0)

### ISSUE THREAD

**Issue by capslockenter** [vtorri/ewpi#27]
Hi,

after building ewpi on Linux (Arch) from the ewpi-1.0.tar.gz and running

`ewpi --efl --prefix=/opt/ewpi_64 --verbose`

the compilation of gst-plugins-base-1.22.1 fails with errors:

```
gst-libs/gst/video/video-orc.c:489:25: error: ‘ORC_ONCE_INIT’ undeclared (first use in this function); 
gst-libs/gst/video/video-orc.c:769:25: error: ‘ORC_ONCE_INIT’ undeclared (first use in this function);
...
```

It seems that in orc-0.4.32/orc/orconce.h this is not defined, but in that header of orc version 0.4.**34** it is.
When copying the orconce.h from the sources of orc-0.4.34 to /opt/ewpi_64/include/orc-0.4/orc/orconce.h
the compilation succeeds.                
The build requirement in gst-plugins-base-1.22.1/meson.build says

orc_req = '>= 0.4.24'

but I don't see how this could work.
I'm not sure if there is some confusion on my side or if it's really an issue with gst-plugins-base and/or orc.
Can someone confirm this behaviour?         

Regards,
Jean Rene

**Comment by vtorri** [comment]
try to use the git repo (i cross compile on fedora without problem, i build the installer on unix too). See NEWS for what will be in ewpi 1.1.

**Comment by capslockenter** [comment]
Thanks, from the git repo it worked. :)

**Comment by vtorri** [comment]
then, closing

**Comment by vtorri** [comment]
@capslockenter btw, there are installers of ewpi and efl, now

**Comment by capslockenter** [comment]
> @capslockenter btw, there are installers of ewpi and efl, now

Thanks. I installed efl-x86_64-win10-1.26.exe in wine. 
When I run elementary_test.exe I get lots of messages that he can't find dlls:

```
$ pwd
/home/bla/.wine/drive_c/users/ploi/Local Settings/Application Data/efl_64/bin
$ wine ./elementary_test.exe
061c:err:module:import_dll Library libintl-8.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\elementary_test.exe") n
ot found
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\elementary_test.e
xe") not found
061c:err:module:import_dll Library libintl-8.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libecore-1.dll") not fo
und
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libecore-1.dll") 
not found
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libefl-1.dll") no
t found
061c:err:module:import_dll Library libiconv.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") not foun
d
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") n
ot found
061c:err:module:import_dll Library libeina-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libefl-1.dll") not foun
d
061c:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not 
found
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not
 found
061c:err:module:import_dll Library libiconv.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") not foun
d
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") n
ot found
061c:err:module:import_dll Library libeina-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not found
061c:err:module:import_dll Library libeo-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libefl-1.dll") not found
061c:err:module:import_dll Library libefl-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libecore-1.dll") not fou
nd
061c:err:module:import_dll Library libiconv.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") not foun
d
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") n
ot found
061c:err:module:import_dll Library libeina-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libecore-1.dll") not fo
und
061c:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not 
found
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not
 found
061c:err:module:import_dll Library libiconv.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") not foun
d
061c:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeina-1.dll") n
ot found
061c:err:module:import_dll Library libeina-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libeo-1.dll") not found
061c:err:module:import_dll Library libeo-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\libecore-1.dll") not foun
d
061c:err:module:import_dll Library libecore-1.dll (which is needed by L"C:\\users\\bla\\Local Settings\\Application Data\\efl_64\\bin\\elementary_test.exe") 
not found
...
```
I also installed it on native Windows 10 and starting elementary_test.exe there doesn't work either.
It says it can't find libintl-8.dll abd libwinpthread-1.dll.
Do these dlls need to be installed separately?

**Comment by vtorri** [comment]
i've never tested with wine. I should do it. But have you installed the ewpi installer in wine too ?

on Windows, indeed  there are missing DLL in latest installer. I am right now updating all the libs in ewpi. I'll provide a new installer soon with the missing DLL

**Comment by capslockenter** [comment]
> i've never tested with wine. I should do it. But have you installed the ewpi installer in wine too ?

Ok, I've installed ewpi-x86_64-win10-1.1.exe in wine now. After pressing the "Finish" button of the installer I get
```
Unhandled exception: illegal instruction in 64-bit code (0x006ffffe574857).
...
Backtrace:
=>0 0x006fffff4c4857 in libexpat-1 (+0x4857) (0x006fffff53892b)
  1 0x006fffff513750 in libfontconfig-1 (+0x23750) (0x00000000000ade)
  2 0x006fffff513f41 in libfontconfig-1 (+0x23f41) (0x007ffffe8909d0)
  3 0x006fffff50457b in libfontconfig-1 (+0x1457b) (0x0000014000b4b4)
  4 0x0000014000925b in fc-cache (+0x925b) (0x0000014000b4b4)
  5 0x000001400013ae in fc-cache (+0x13ae) (0x007ffffe892800)
  6 0x000001400014e6 in fc-cache (+0x14e6) (0000000000000000)
  7 0x006ffffff08a69 in kernel32 (+0x28a69) (0000000000000000)
  8 0x006ffffffad485 in ntdll (+0x5d485) (0000000000000000)
...
```
When I start elementary_test.exe he at least doesn't complain about missing dlls anymore :)
but it throws a similar exception as the installer.
But edje_player.exe for example works :)

> on Windows, indeed there are missing DLL in latest installer. I am right now updating all the libs in ewpi. I'll provide a new installer soon with the missing DLL

After I installed ewpi in Windows 10, elementary_test.exe successfully starts :)

**Comment by capslockenter** [comment]
> Ok, I've installed ewpi-x86_64-win10-1.1.exe in wine now. After pressing the "Finish" button of the installer I get
> 
> ```
> Unhandled exception: illegal instruction in 64-bit code (0x006ffffe574857).
> ...
> Backtrace:
> =>0 0x006fffff4c4857 in libexpat-1 (+0x4857) (0x006fffff53892b)
>   1 0x006fffff513750 in libfontconfig-1 (+0x23750) (0x00000000000ade)
>   2 0x006fffff513f41 in libfontconfig-1 (+0x23f41) (0x007ffffe8909d0)
>   3 0x006fffff50457b in libfontconfig-1 (+0x1457b) (0x0000014000b4b4)
>   4 0x0000014000925b in fc-cache (+0x925b) (0x0000014000b4b4)
>   5 0x000001400013ae in fc-cache (+0x13ae) (0x007ffffe892800)
>   6 0x000001400014e6 in fc-cache (+0x14e6) (0000000000000000)
>   7 0x006ffffff08a69 in kernel32 (+0x28a69) (0000000000000000)
>   8 0x006ffffffad485 in ntdll (+0x5d485) (0000000000000000)
> ...
> ```
Ah, turns out the CPU here doesn't support AVX and it is an AVX instruction which is trying to execute here.
Running the same on a more recent CPU works fine :)

**Comment by vtorri** [comment]
that is good news :-)

**Comment by vtorri** [comment]
btw, you can set the arch with --arch, when using ewpi (see ewpi --help). It will be passed to the compiler
