### ISSUE TITLE
Why should I use this tool?

### ISSUE THREAD

**Issue by ghost** [vtorri/ewpi#29]
MSYS2 has native packages for EFL:

https://packages.msys2.org/base/mingw-w64-efl

It's 1.27, newer than your latest release that is only at 1.26.

Btw, the description of your project is a bit misleading. `EFL Windows package installer`. But if people scrolling a bit down they will see that it also supports Linux.

**Comment by vtorri** [comment]
thanks for your support

1. basically, it's for me
2. the final purpose is an NSIS installer, so no need to install msys2
3. linux part is for cross compilation, which I use to avoid viruses when I create NSIS installers. I'll update README
4. for the next release, I have some problems with my computers, normally I will do one in september

I'm wondering how you find my project...

**Comment by ghost** [comment]
> I'm wondering how you find my project...

I found you on the list of contributors to the muon project. It seems you have given up on muon, don't you?

**Comment by vtorri** [comment]
yes, it seems that lattis is just ignoring my last PRs while not ignoring others, even if I wrote the windows port of muon...
I'll do a muon fork with my last work on Windows compilers (cl, intel cpx, windows resource and other fixes)

**Comment by ghost** [comment]
It seems he doesn't like Windows.

**Comment by ghost** [comment]
> yes, it seems that lattis is just ignoring my last PRs while not ignoring others, even if I wrote the windows port of muon... I'll do a muon fork with my last work on Windows compilers (cl, intel cpx, windows resource and other fixes)

I'm looking forward to your muon fork, btw.
