### ISSUE TITLE
Redefined boolean during EFL build

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#3]
When compiling EFL I run into this error where boolean is defined as two different types:
`
CC

       lib/emile/lib_emile_libemile_la-emile_image.lo
In file included from /root/EFL/ewpi_64/include/jpeglib.h:31:0,
                 from lib/emile/emile_image.c:25:
/root/EFL/ewpi_64/include/jmorecfg.h:242:13: error: conflicting types for 'boolean'
 typedef int boolean;
             ^~~~~~~
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wtypes.h:8:0,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/winscard.h:10,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/windows.h:97,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/winsock2.h:23,
                 from lib/emile/emile_image.c:10:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/rpcndr.h:65:25: note: previous declaration of 'boolean' was here
   typedef unsigned char boolean;
                         ^~~~~~~
`
Making them the same type works around the issue but at least one comes from the ewpi include folder. Not sure which one you want to have here.

**Comment by vtorri** [comment]
ok, i will see how to fix that

**Comment by vtorri** [comment]
normally, in emile_image.c, you can regroup the #ifdef _WIN32, and add another #define for libjpeg : 

\#ifdef \_WIN32
\# include <winsock2.h>
\# include <Evil.h>
\# define HAVE\_BOOLEAN /* This prevents libjpeg to redefine boolean */
\# define XMD\_H /* This prevents libjpeg to redefine INT32 */
\#endif

**Comment by Stefan-Schmidt** [comment]
Thanks, that worked like a charm. Added a patch to my queue for mingw ci support
https://git.enlightenment.org/core/efl.git/commit/?h=devs/stefan/ci-mingw&id=ea1d2efa6232a89e1d28b12dec5efdee1d3d988e
