### ISSUE TITLE
Wrong libname in luajit pc file results in failed linking

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#4]
In the luajit install.sh file the sonames of the lib are set like this:
34     FILE_SO=lua51.dll \
35     INSTALL_SONAME=lua51.dll \
36     TARGET_XSHLDFLAGS="-shared -Wl,--out-implib,liblua.dll.a" \
37     INSTALL_SOSHORT1=liblua.dll.a \

The luajit pc file still refers a different name though:
 12 libname=luajit-${abiver}

This made the efl compile ail for me until I changed the pc file to use liblua as libname as well.

**Comment by vtorri** [comment]
should be fixed. Please test

**Comment by Stefan-Schmidt** [comment]
After your latest fixes this is working now
