### ISSUE TITLE
bullet package does not build with missing -ldl

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#5]
The bullet package does not build over a missing -ldl for linking

 /usr/lib64/ccache/x86_64-w64-mingw32-g++  -isystem /home/stefan/EFL/ewpi/packages/bullet/bullet3-2.87/src -O2 -DNDEBUG  -shared -o ../../lib/libBullet3OpenCL_clew.dll -Wl,--out-implib,../../lib/libBullet3OpenCL_clew.dll.a -Wl,--major-image-version,2,--minor-image-version,87 -Wl,--w    hole-archive CMakeFiles/Bullet3OpenCL_clew.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/Bullet3OpenCL_clew.dir/linklibs.rsp
/usr/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status

**Comment by vtorri** [comment]
ok, i have to add -ldl when i'm not on Windows :-)

**Comment by vtorri** [comment]
i also get it when cross compiling on fedora. I don't know how to fix that, though... cmake is a piece of ####

**Comment by Stefan-Schmidt** [comment]
Fixed by Vincent in commit e4b16c8c3ffd57a2f22967c8135838356f22d753
