### ISSUE TITLE
gstreamer package does not configure with missing glib cross dep

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#6]
98 Library gmp found: NO
 99 Library gsl found: NO
100 Library gslcblas found: NO
101 Library dl found: NO
102 Checking for function "dladdr" : NO
103 Cross dependency glib-2.0 found: NO
104 Looking for a fallback subproject for the dependency glib-2.0
105 Couldn't use fallback subproject in subprojects/glib for the dependency glib-2.0
106 Reason: Subproject directory 'subprojects/glib' does not exist and cannot be downloaded:
107 No glib.wrap found for 'subprojects/glib'
108
109 meson.build:386:0: ERROR:  Pkg-config not found.
110
111 A full log can be found at /home/stefan/EFL/ewpi/packages/gstreamer/gstreamer-1.14.4/builddir/meson-logs/meson-log.txt

**Comment by vtorri** [comment]
i should add -ldl too here, btw
pkg-config is not found, here. I have to update the PATH, like in gst-plugins-base/install.sh

**Comment by vtorri** [comment]
well, thee problem is that it does not find x86_64-w64-mingw32-pkg-config (without.exe) which is indeed not in PATH. But I don't understand how a windows binary can help on a linux system...

**Comment by vtorri** [comment]
pkg-config is found now, but the problem is that meson has installed glib2 libraries and pc files in $prefix/lib64(/pkgconfig) when compiling for 64 bits
2 solutions
 * i move $prefix/lib64 to $prefix/lib
 * i set $libdir to $prefix/lib64 for all the other libraries

I have no strong opinion, here. what do you prefer ?

**Comment by vtorri** [comment]
i added --libdir=lib to meson call for glib2, gst and gst-plugins-base and it seems to work on linux

I  had to install flex and bison on my fedora distro though

**Comment by Stefan-Schmidt** [comment]
Verified that it works for me now.
