### ISSUE TITLE
libtheora package linking fails with syntax error in linker script

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#7]
libtheora: compilingMaking install in lib
make[1]: Entering directory '/home/stefan/EFL/ewpi/packages/libtheora/libtheora-1.1.1/lib'
/bin/sh ../libtool --mode=link x86_64-w64-mingw32-gcc -I/home/stefan/EFL/ewpi_64/include   -Wall -Wno-parentheses -O3 -fforce-addr -fomit-frame-pointer -finline-functions -funroll-loops   -L/home/stefan/EFL/ewpi_64//lib -o libtheoradec.la -rpath /home/stefan/EFL/ewpi_64/lib -version-info 2:4:1 -no-undefined -export-symbols ../win32/xmingw32/libtheoradec-all.def  apiwrapper.lo bitpack.lo decapiwrapper.lo decinfo.lo decode.lo dequant.lo fragment.lo huffdec.lo idct.lo info.lo internal.lo quant.lo state.lo mmxidct.lo mmxfrag.lo mmxstate.lo x86state.lo
libtool: link: rm -fr  .libs/libtheoradec.def .libs/libtheoradec.exp .libs/libtheoradec.filter
libtool: link: /usr/bin/x86_64-w64-mingw32-nm -B  .libs/apiwrapper.o .libs/bitpack.o .libs/decapiwrapper.o .libs/decinfo.o .libs/decode.o .libs/dequant.o .libs/fragment.o .libs/huffdec.o .libs/idct.o .libs/info.o .libs/internal.o .libs/quant.o .libs/state.o .libs/mmxidct.o .libs/mmxfrag.o .libs/mmxstate.o .libs/x86state.o   | sed -n -e 's/^.*[      ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[         ][      ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' | /usr/bin/sed -e '/^[BCDGRS][ ]/s/.*[ ]\([^ ]*\)/\1 DATA/' | /usr/bin/sed -e '/^[AITW][ ]/s/.*[ ]//' | sort | uniq > .libs/libtheoradec.exp
libtool: link: if test "x`/usr/bin/sed 1q .libs/libtheoradec.def`" = xEXPORTS; then cp .libs/libtheoradec.def .libs/libtheoradec-1.dll.def; else echo EXPORTS > .libs/libtheoradec-1.dll.def; cat .libs/libtheoradec.def >> .libs/libtheoradec-1.dll.def; fi
libtool: link:  x86_64-w64-mingw32-gcc -shared .libs/libtheoradec-1.dll.def  .libs/apiwrapper.o .libs/bitpack.o .libs/decapiwrapper.o .libs/decinfo.o .libs/decode.o .libs/dequant.o .libs/fragment.o .libs/huffdec.o .libs/idct.o .libs/info.o .libs/internal.o .libs/quant.o .libs/state.o .libs/mmxidct.o .libs/mmxfrag.o .libs/mmxstate.o .libs/x86state.o   -L/home/stefan/EFL/ewpi_64//lib    -o .libs/libtheoradec-1.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libtheoradec.dll.a
/usr/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld: .libs/libtheoradec-1.dll.def:3: syntax error
/usr/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld:.libs/libtheoradec-1.dll.def: file format not recognized; treating as linker script
/usr/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld:.libs/libtheoradec-1.dll.def:2: syntax error
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:468: libtheoradec.la] Error 1
make[1]: Leaving directory '/home/stefan/EFL/ewpi/packages/libtheora/libtheora-1.1.1/lib'
make: *** [Makefile:291: install-recursive] Error 1
libtheora: installed (ret=512)

**Comment by vtorri** [comment]
i have to look at this. No idea why there is a problem with the .def

**Comment by vtorri** [comment]
same problem when cross compiling on fedora

**Comment by Stefan-Schmidt** [comment]
Vicent fixed it with 93145793ca957b0f0089f30f7fe1f0263e2c76da
