### ISSUE TITLE
libwebp package compile fials with invalid libtool archive

### ISSUE THREAD

**Issue by Stefan-Schmidt** [vtorri/ewpi#8]
Making install in imageio
make[1]: Entering directory '/home/stefan/EFL/ewpi/packages/libwebp/libwebp-1.0.0/imageio'
  CCLD     libimagedec.la
/usr/bin/grep: /home/stefan/EFL/efl/ewpi/packages/libwebp/libwebp-1.0.0/src/libwebp.la: No such file or directory
/usr/bin/sed: can't read /home/stefan/EFL/efl/ewpi/packages/libwebp/libwebp-1.0.0/src/libwebp.la: No such file or directory
libtool:   error: '/home/stefan/EFL/efl/ewpi/packages/libwebp/libwebp-1.0.0/src/libwebp.la' is not a valid libtool archive
make[1]: *** [Makefile:391: libimagedec.la] Error 1
make[1]: Leaving directory '/home/stefan/EFL/ewpi/packages/libwebp/libwebp-1.0.0/imageio'
make: *** [Makefile:422: install-recursive] Error 1
libwebp: installed (ret=512)

**Comment by vtorri** [comment]
strange, i'll look at it

**Comment by vtorri** [comment]
no problem on my fedora...

**Comment by vtorri** [comment]
i've rebuilt everything from the beginning, cross compiling on a fedora : it works for me

**Comment by Stefan-Schmidt** [comment]
Sorry, my fault. It was due to a stall file around. I did not clean up everything. Working now.
